version: 1.0.{build}
image: Visual Studio 2017
environment:
    COVERALLS_REPO_TOKEN:
        secure: 8OEWiuH67VRfNi5Ken9olVpzE41uBHQ6+wyr/f6MCMQEvRJsA1M1qXepXmEt0zJj
before_build:
    - ps: nuget restore ./MvcPWy.sln
build:
    project: MvcPWy.sln
test_script:
#  - ps: '&"./packages/OpenCover.4.6.519/tools/OpenCover.Console.exe" -register:user -target:"${env:ProgramFiles(x86)}/Microsoft Visual Studio/2017/Community/Common7/IDE/MSTest.exe" -targetargs:"/testcontainer:MvcPWy.Tests/bin/Debug/MvcPWy.Tests.dll" -output:coverage.xml'
#  - ps: '&"./packages/coveralls.net.0.7.0/tools/csmacnz.Coveralls.exe" --opencover -i coverage.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID'